name: ivt
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.8
  - pip
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - igl
  - imageio
  - stevedore
  - lxml
  - matplotlib
  - gin
  - pip:
    - cholespy
    - largesteps
    - xatlas
    - pymeshfix
    - gpytoolbox